// Make the pair of keys that lets this server send notifications. Run it once, ever:
//   node scripts/vapid-keys.js           # print the lines, to paste into .env yourself
//   node scripts/vapid-keys.js --write   # add them to .env here, printing no secret
//
// Nothing is registered anywhere and nobody is paid. The keys are only how Apple's and
// Google's push services recognise notices as coming from this server and not someone
// pretending to be it. Keep the private one secret; the public one is handed to every
// browser that switches notifications on.
//
// Replacing them later logs every device out of notifications: the subscriptions already
// saved are tied to the old public key and would start failing, and everyone would have
// to tap Allow again. So --write refuses if there is already a key in .env, rather than
// quietly costing everyone their notifications.
import { appendFileSync, readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import webpush from 'web-push';

const ENV = `${fileURLToPath(new URL('..', import.meta.url))}.env`;
const SUBJECT = process.env.VAPID_SUBJECT || 'mailto:admin@ainalreempro.com';
const { publicKey, privateKey } = webpush.generateVAPIDKeys();

if (!process.argv.includes('--write')) {
  console.log(`
Add these three lines to ${ENV}, then restart the server:

VAPID_PUBLIC_KEY=${publicKey}
VAPID_PRIVATE_KEY=${privateKey}
VAPID_SUBJECT=${SUBJECT}

The last one is just an address a push service can complain to. Change it if you like.
Or run this again with --write and it will add them for you.
`);
  process.exit(0);
}

if (!existsSync(ENV)) {
  console.error(`There is no .env at ${ENV}. Create it first — this script only adds to one that exists.`);
  process.exit(1);
}
if (/^VAPID_PRIVATE_KEY=.+/m.test(readFileSync(ENV, 'utf8'))) {
  console.error('This .env already has notification keys, and replacing them would switch every device off.\n' +
    'Nothing was changed. Remove the VAPID_ lines by hand first if you really mean to start again.');
  process.exit(1);
}

appendFileSync(ENV, `\n# Web push. Generated by scripts/vapid-keys.js — see the README.\nVAPID_PUBLIC_KEY=${publicKey}\nVAPID_PRIVATE_KEY=${privateKey}\nVAPID_SUBJECT=${SUBJECT}\n`);
console.log('Notification keys added to .env. Restart the server and they take effect. (No secret was printed.)');
